### ISSUE TITLE
Axios responses.

### ISSUE THREAD

**Issue by audetcameron** [helloiamlukas/laravel-chrome#3]
Is there any way to wait for axios responses?

**Comment by helloiamlukas** [comment]
I'm not sure what you mean by that. By default chrome headless is waiting for all asynchronous javascript requests to finish. Maybe you can provide an example?

**Comment by audetcameron** [comment]
I had an axios call return a promise then run another axios call for some extra data, it was appearing to render prior to the second response.  Very nice package though.

**Comment by helloiamlukas** [comment]
Hmm, this is not really related to this package then. Looks like this some issue with Chrome headless.
