### ISSUE TITLE
Update to support PHP 8 and Laravel 8

### ISSUE THREAD

**Issue by WadeShuler** [helloiamlukas/laravel-chrome#4]
Received:

```bash
[InvalidArgumentException]
  Package helloiamlukas/laravel-chrome has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
```

I am running PHP v8.0.3 with a fresh Laravel v8.56.0 install.

If there isn't a reason for the restriction (ie: chromium version compatibility issues), then `composer.json` needs to be updated to allow current versions.

Here is a version snip of relevant deps from my composer json file:

```json
"require": {
        "php": "^7.3|^8.0"
},

"require-dev": {
        "phpunit/phpunit": "^9.3.3"
}
```

**Comment by helloiamlukas** [comment]
Hello!
Sorry, this package is out of date and will be archived. Feel free to fork it and update the code for PHP8 :)
